# Usar imagem oficial do Bun
FROM oven/bun:1.1.13 AS base

# Criar diretório de trabalho
WORKDIR /usr/src/app

# Copiar arquivos de dependência
COPY bun.lockb package.json prisma ./

# Instalar dependências com Bun
RUN bun install --frozen-lockfile

# Copiar restante da aplicação
COPY . .

# Rodar migrations usando Bun
CMD ["bun", "run", "migrate"]