name: Run Migrations

on:
  push:
    branches:
      - main

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configuração do Docker Compose
      - name: Set up Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      # 3. Build das imagens Docker (caso necessário)
      - name: Build Docker images
        run: |
          docker-compose build

      # 4. Rodar as migrations no banco de dados
      - name: Run database migrations
        run: |
          docker-compose run --rm api pnpm run migrate
